/*
28. CREAR UNA VISTA LLAMADA VENDEDORES A QUE INCLUIRÁ TODOS LOS VENDEDORES
DEL GRUPO QUE SE LLAME "VENDORES A"
*/
CREATE VIEW vendedoresd AS
    SELECT id, nombre
    FROM vendedores
    WHERE grupo_id IN (SELECT id FROM grupos WHERE nombre = 'VENDEDORES D');
   