#Mostrar todos los registros /filas de una tabla#


SELECT email, nombre, apellido FROM usuarios;

#OPERADORES ARITMETICOS#
SELECT email, (4+7) AS 'OPERACION' FROM usuarios;


#FUNCIONES MATEMATICAS#

SELECT ABS(7) AS 'OPERACION' FROM USUARIO;

#REDONDEAR VALOR A 8#
SELECT CEIL(7.34) AS 'OPERACIONES' FROM USUARIO;

